# Generated by Django 4.2.11 on 2025-09-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contents', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
